Review-Site/Areas/Admin/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Review_Site.Data.Models;
using Review_Site.Core;
using Review_Site.Areas.Admin.Models;
using Review_Site.Data;

namespace Review_Site.Areas.Admin.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private DataContext db = new DataContext();

        #region Browsers and Details

        [Restrict(Identifier = "Admin.Article.Index")]
        public ViewResult Index()
        {
            var articles = db.Articles.Get();
            return View(articles.OrderBy(x => x.Title).ToList());
        }

        [Restrict(Identifier = "Admin.Article.Index")]
        public ActionResult MiniBrowser()
        {
            return View(db.Articles.Get().ToList());
        }

        [Restrict(Identifier = "Admin.Article.Index")]
        public ViewResult Details(Guid id)
        {
            Article article = db.Articles.Get(id);
            return View(article);
        }
        #endregion

        #region Create
        [Restrict(Identifier = "Admin.Article.Create")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories.Get(), "ID", "Title");
            ViewBag.TagList = db.Tags.Get().Select(x => x.Name).ToList();
            return View();
        }

        [HttpPost]
        [Restrict(Identifier = "Admin.Article.Create")]
        public ActionResult Create(Article article, string tagList)
        {
            var tagNameList = (tagList ?? "").Split(',').ToList();
            foreach (var s in tagNameList.Where(s => !String.IsNullOrEmpty(s)))
            {
                if (db.Tags.Any(x => x.Name.ToLower() == s.ToLower()))
                {
                    article.Tags.Add(db.Tags.Single(x => x.Name.ToLower() == s.ToLower()));
                }
                else
                {
                    var tag = new Tag
                                  {
                                      ID = Guid.NewGuid(),
                                      Name = s
                                  };
                    db.Tags.AddOrUpdate(tag);
                    article.Tags.Add(tag);
                }
            }

            if (ModelState.IsValid)
            {
                if (db.Articles.Any(x => x.Title == article.Title))
                {
                    ModelState.AddModelError("Title", "An Article already exists with that title.");
                    ViewBag.CategoryID = new SelectList(db.Categories.Get(), "ID", "Title", article.Category == null ? (Guid?)null : article.Category.ID);
                    ViewBag.TagList = db.Tags.Get().Select(x => x.Name).ToList();
                    return View(article);
                }
                article.ID = Guid.NewGuid();
                DateTime currentTime = DateTime.Now;
                article.LastModified = currentTime;
                article.Created = currentTime;
                article.Author = db.Users.Get(SiteAuthentication.GetUserCookie().ID);
                db.Articles.Add(article);

                LuceneSearch.AddUpdate(article);

                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories.Get(), "ID", "Title", article.Category == null ? (Guid?)null : article.Category.ID);
            ViewBag.TagList = db.Tags.Get().Select(x => x.Name).ToList();
            return View(article);
        }
        #endregion

        #region Edit
        [Restrict(Identifier = "Admin.Article.Edit")]
        public ActionResult Edit(Guid id)
        {
            Article article = db.Articles.Single(a => a.ID == id);
            ViewBag.CategoryID = new SelectList(db.Categories.Get(), "ID", "Title", article.Category == null ? (Guid?)null : article.Category.ID);
            ViewBag.AuthorID = new SelectList(db.Users.Get(), "ID", "FullName", article.Author.ID);
            ViewBag.TagList = db.Tags.Get().Select(x => x.Name).ToList();
            return View(article);
        }

        [HttpPost]
        [Restrict(Identifier = "Admin.Article.Edit")]
        public ActionResult Edit(Article article, string tagList)
        {
            if (ModelState.IsValid)
            {
                if (db.Articles.Any(x => x.Title == article.Title && x.ID != article.ID))
                {
                    ModelState.AddModelError("Title", "Another Article exists with that title.");
                    ViewBag.CategoryID = new SelectList(db.Categories.Get(), "ID", "Title", article.Category == null ? (Guid?)null : article.Category.ID);
                    ViewBag.AuthorID = new SelectList(db.Users.Get(), "ID", "FullName", article.Author.ID);
                    ViewBag.TagList = db.Tags.Get().Select(x => x.Name).ToList();
                    return View(article);
                }
                article.Tags.Clear();
                List<String> tagNameList = tagList.Split(',').ToList();
                foreach (String s in tagNameList)
                {
                    if (String.IsNullOrEmpty(s)) continue;
                    if (db.Tags.Any(x => x.Name.ToLower() == s.ToLower()))
                    {
                        article.Tags.Add(db.Tags.Single(x => x.Name.ToLower() == s.ToLower()));
                    }
                    else
                    {
                        Tag tag = new Tag
                        {
                            ID = Guid.NewGuid(),
                            Name = s
                        };
                        article.Tags.Add(tag);
                    }
                }
                article.LastModified = DateTime.Now;
                db.Articles.Update(article);
                LuceneSearch.AddUpdate(article);

                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories.Get(), "ID", "Title", article.Category == null ? (Guid?)null : article.Category.ID);
            ViewBag.AuthorID = new SelectList(db.Users.Get(), "ID", "FullName", article.Author.ID);
            ViewBag.TagList = db.Tags.Get().Select(x => x.Name).ToList();
            return View(article);
        }
        #endregion

        #region Delete
        [Restrict(Identifier = "Admin.Article.Delete")]
        public ActionResult Delete(Guid id)
        {
            Article article = db.Articles.Single(a => a.ID == id);
            return View(article);
        }

        //
        // POST: /Admin/Article/Delete/5

        [HttpPost, ActionName("Delete")]
        [Restrict(Identifier = "Admin.Article.Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Article article = db.Articles.Single(a => a.ID == id);
            db.Articles.Delete(article);

            LuceneSearch.Remove(id);

            return RedirectToAction("Index");
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Review-Site/Areas/Admin/Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Review_Site.Data.Models;
using System.IO;
using Review_Site.Core;
using Review_Site.Areas.Admin.Models;
using Review_Site.Data;
using System.Web.Helpers;

namespace Review_Site.Areas.Admin.Controllers
{ 
    [Authorize]
    public class ResourceController : Controller
    {
        private DataContext db = new DataContext();
        #region Browse and Details
        [Restrict(Identifier = "Admin.Resource.Index")]
        public ViewResult Index()
        {
            return View(db.Resources.Get().OrderBy(x => x.Title).ToList());
        }

        [Restrict(Identifier = "Admin.Resource.Index")]
        public ViewResult Details(Guid id)
        {
            Resource resource = db.Resources.Get(id);
            return View(resource);
        }
        #endregion

        #region Upload
        [Restrict(Identifier = "Admin.Resource.Upload")]
        public ActionResult Upload()
        {
            ViewBag.SourceTextColorID = new SelectList(db.Colors.Get(), "ID", "Name");
            return View();
        }

        [HttpPost]
        [Restrict(Identifier = "Admin.Resource.Upload")]
        public ActionResult Upload(Resource resource, HttpPostedFileBase file)
        {
            resource.ID = Guid.NewGuid();
            string fileName = "";
            if (db.Resources.Any(x => x.Title == resource.Title))
            {
                ModelState.AddModelError("Title", "A Resource with that Title already exists.");
                return View(resource);
            }
            if (file != null && file.ContentLength > 0)
            {
                resource.Type = file.ContentType;
                resource.Creator = db.Users.Get(SiteAuthentication.GetUserCookie().ID);
                resource.DateAdded = DateTime.Now;
                resource.LastModified = DateTime.Now;
                fileName = resource.ID.ToString();
            }
            else
            {
                ModelState.AddModelError("", "You must provide a file to upload!");
                return View(resource);
            }
            if (ModelState.IsValid)
            {
                var path = Path.Combine(Server.MapPath("~/ResourceUploads"), fileName);
                file.SaveAs(path);
                db.Resources.AddOrUpdate(resource);
                return RedirectToAction("Index");  
            }

            ViewBag.SourceTextColorID = new SelectList(db.Colors.Get(), "ID", "Name");
            return View(resource);
        }

        [Restrict(Identifier = "Admin.Resource.Upload")]
        public ActionResult MiniUpload()
        {
            ViewBag.SourceTextColorID = new SelectList(db.Colors.Get(), "ID", "Name");
            return View();
        }

        [HttpPost]
        [Restrict(Identifier = "Admin.Resource.Upload")]
        public ActionResult MiniUpload(Resource resource, HttpPostedFileBase file)
        {
            resource.ID = Guid.NewGuid();
            string fileName = "";
            if (file != null && file.ContentLength > 0)
            {
                resource.Type = file.ContentType;
                resource.Creator = db.Users.Get(SiteAuthentication.GetUserCookie().ID);
                resource.DateAdded = DateTime.Now;
                fileName = resource.ID.ToString();
            }
            else
            {
                ModelState.AddModelError("", "You must provide a file to upload!");
                return View(resource);
            }
            if (ModelState.IsValid)
            {
                var path = Path.Combine(Server.MapPath("~/ResourceUploads"), fileName);
                file.SaveAs(path);
                db.Resources.AddOrUpdate(resource);
                return RedirectToAction("MiniBrowser");
            }

            return View(resource);
        }

        #endregion

        #region Edit

        //
        // GET: /Admin/Resource/Edit/5

        [Restrict(Identifier = "Admin.Resource.Edit")]
        public ActionResult Edit(Guid id)
        {
            Resource resource = db.Resources.Single(r => r.ID == id);
            ViewBag.SourceTextColorID = new SelectList(db.Colors.Get(), "ID", "Name", resource.SourceTextColor.ID);
            return View(resource);
        }

        //
        // POST: /Admin/Resource/Edit/5

        [HttpPost]
        [Restrict(Identifier = "Admin.Resource.Edit")]
        public ActionResult Edit(Resource resource)
        {
            if (ModelState.IsValid)
            {
                if (db.Resources.Any(x => x.Title == resource.Title && x.ID != resource.ID))
                {
                    ModelState.AddModelError("Title", "A Resource with that Title already exists.");
                    ViewBag.SourceTextColorID = new SelectList(db.Colors.Get(), "ID", "Name", resource.SourceTextColor.ID);
                    return View(resource);
                }
                resource.LastModified = DateTime.Now;
                db.Resources.AddOrUpdate(resource);
                return RedirectToAction("Index");
            }
            ViewBag.SourceTextColorID = new SelectList(db.Colors.Get(), "ID", "Name", resource.SourceTextColor.ID);
            return View(resource);
        }
        #endregion

        #region Delete
        // This is confirmed in a JS modal in the webadmin
        [Restrict(Identifier = "Admin.Resource.Delete")]
        public ActionResult Delete(Guid id)
        {
            Resource resource = db.Resources.Single(r => r.ID == id);
            var path = Path.Combine(Server.MapPath("~/ResourceUploads"), resource.ID.ToString());
            if(System.IO.File.Exists(path)) System.IO.File.Delete(path);
            db.Resources.Delete(resource);
            return RedirectToAction("Index");
        }
        #endregion

        #region Other Browsers
        [Restrict(Identifier = "Admin.Resource.Index")]
        public ActionResult MiniBrowser(string filter)
        {
            List<Resource> result;
            if (!String.IsNullOrEmpty(filter)) result = db.Resources.Get().Where(x => x.Type.StartsWith(filter)).ToList();
            else result = db.Resources.Get().OrderBy(x => x.Title).ToList();

            return View(result);
        }

        [Restrict(Identifier = "Admin.Resource.Index")]
        public ActionResult CKEditorBrowser()
        {
            ViewBag.CKEditor = true;
            return View("MiniBrowser", db.Resources.Get().ToList());
        }
        #endregion

        #region Crop
        [Restrict(Identifier = "Admin.Resource.Crop")]
        public ActionResult Crop(Guid id)
        {
            if (!db.Resources.Any(x => x.ID == id)) throw new HttpException(404, "Resource not found.");
            Resource res = db.Resources.Get(id);
            if (!res.Type.StartsWith("image")) return Content("You cannot crop a non-image resource!");

            string path = Path.Combine(Server.MapPath("~/ResourceUploads"), id.ToString());
            FileStream stream = new FileStream(path, FileMode.Open);
            if (stream.Length == 0) throw new HttpException(503, "An internal server error occured whilst fetching the resource.");

            byte[] streamBytes = new byte[stream.Length];
            stream.Read(streamBytes, 0, (int)stream.Length);
            stream.Close();

            WebImage img = new WebImage(streamBytes);
            CropForm form = new CropForm
            {
                ResourceID = id,
                Type = res.Type,
                Source = res.Source,
                SourceTextColorID = res.SourceTextColor.ID,
                OrigWidth = img.Width,
                OrigHeight = img.Height
            };
            return View(form);
        }

        [HttpPost]
        [Restrict(Identifier = "Admin.Resource.Crop")]
        public ActionResult Crop(CropForm form)
        {
            if (form.x <= 0 && form.y <= 0 && form.x2 <= 0 && form.y2 <= 0)
            {
                ModelState.AddModelError("", "You must provide a selection!");
                return View(form);
            }

            if (db.Resources.Any(x => x.Title == form.Title))
            {
                ModelState.AddModelError("Title", "Another Resource has this Title.");
                return View(form);
            }

            string oldImagePath = Path.Combine(Server.MapPath("~/ResourceUploads"), form.ResourceID.ToString());
            FileStream stream = new FileStream(oldImagePath, FileMode.Open);

            WebImage image = new WebImage(stream);

            int width = image.Width;
            int height = image.Height;

            image.Crop((int)Math.Ceiling(form.y), (int)Math.Ceiling(form.x), height - (int)Math.Ceiling(form.y2), width - (int)Math.Ceiling(form.x2));
            //image.Crop((int)form.y, (int)form.x, (int)form.y2, (int)form.x2);

            Resource newResource = new Resource
            {
                ID = Guid.NewGuid(),
                Title = form.Title,
                Creator = db.Users.Get(SiteAuthentication.GetUserCookie().ID),
                DateAdded = DateTime.Now,
                Type = form.Type,
                Source = form.Source,
                SourceTextColor = db.Colors.Get(form.SourceTextColorID.Value)
            };

            string newImagePath = Path.Combine(Server.MapPath("~/ResourceUploads"), newResource.ID.ToString());

            image.Save(newImagePath, null, false);
            db.Resources.AddOrUpdate(newResource);
            return View("_CloseAndRefreshParent");
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Review-Site/Areas/Admin/Views/GridElement/Create.cshtml
@model Review_Site.Data.Models.GridElement

@{
    ViewBag.Title = "Create";
}

<h2>Create New Grid Element</h2>

@{
    ViewBag.ButtonText = "Create Element";
    Html.RenderPartial("_Form", Model);
}

Review-Site/Areas/Admin/Views/GridElement/Delete.cshtml
@model Review_Site.Data.Models.GridElement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>GridElement</legend>

    <div class="display-label">Color</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BorderColor.Name)
    </div>

    <div class="display-label">Article</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Article.Title)
    </div>

    <div class="display-label">Grid</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Grid.Name)
    </div>

    <div class="display-label">Resource</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Image.Title)
    </div>

    <div class="display-label">SizeClass</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SizeClass)
    </div>

    <div class="display-label">HeadingClass</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HeadingClass)
    </div>

    <div class="display-label">InverseHeading</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InverseHeading)
    </div>

    <div class="display-label">HeadingText</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HeadingText)
    </div>

    <div class="display-label">Width</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Width)
    </div>

    <div class="display-label">UseHeadingText</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UseHeadingText)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Review-Site/Areas/Admin/Views/GridElement/Details.cshtml
@model Review_Site.Data.Models.GridElement

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>GridElement</legend>

    <div class="display-label">BorderColorID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BorderColorID)
    </div>

    <div class="display-label">ArticleID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ArticleID)
    </div>

    <div class="display-label">GridID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GridID)
    </div>

    <div class="display-label">Image Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Image.Title)
    </div>

    <div class="display-label">SizeClass</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SizeClass)
    </div>

    <div class="display-label">HeadingClass</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HeadingClass)
    </div>

    <div class="display-label">InverseHeading</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InverseHeading)
    </div>

    <div class="display-label">HeadingText</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HeadingText)
    </div>

    <div class="display-label">Width</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Width)
    </div>

    <div class="display-label">UseHeadingText</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UseHeadingText)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Review-Site/Areas/Admin/Views/GridElement/Edit.cshtml
@model Review_Site.Data.Models.GridElement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Grid Element</h2>

@{
    ViewBag.ButtonText = "Save Changes";
    ViewBag.IDField = true;
    Html.RenderPartial("_Form", Model);
}

Review-Site/Areas/Admin/Views/GridElement/Index.cshtml
@model IEnumerable<Review_Site.Data.Models.GridElement>

@{
    ViewBag.Title = "Grid Elements";
}

<h2>Grid Elements@(!String.IsNullOrEmpty(ViewBag.GridName) ? " from Grid \"" + ViewBag.GridName + "\"": "")</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-striped table-bordered table-condensed">
    <tr>
        <th>
            Article
        </th>
        <th>
            Colour
        </th>
        <th>
            Grid
        </th>
        <th>
            Size
        </th>
        <th>
            HeadingClass
        </th>
        <th>
            InverseHeading
        </th>
        <th>
            Width
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Article.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BorderColor.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grid.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SizeClass)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HeadingClass)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InverseHeading)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Width)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

@if (!Model.Any())
{
    <tr>
        <td colspan="8" style="text-align: center"><strong>There is nothing here.</strong></td>
    </tr>
}

</table>

Review-Site/Areas/Admin/Views/GridElement/_Form.cshtml
@model Review_Site.Data.Models.GridElement
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    if (ViewBag.IDField == true)
    {
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.LastModified)
    }
        <ul class="nav nav-tabs" id="formTabs">
            <li class="active"><a href="#basic" data-toggle="tab">Basic</a></li>
            <li><a href="#visual-styling" data-toggle="tab">Visual Styling</a></li>
            <li><a href="#position" data-toggle="tab">Position</a></li>
            <li><a href="#advanced" data-toggle="tab">Advanced</a></li>
        </ul>
    
        <div class="tab-content">
            <div class="tab-pane active" id="basic">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Grid.ID, "Parent Grid")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("Grid.ID", (SelectList)ViewBag.GridIDs, String.Empty)
                    @Html.ValidationMessageFor(model => model.Grid.ID, "You must choose a Grid to use.")
                </div>
                <div class="editor-label">
                    <p>Selected Article: <span id="selectedArticle">@((Model == null || Model.Article == null) ? "None" : Model.Article.Title)</span></p>
                    <a class="btn" href="#" onclick="openArticleSelector()">Select Article</a>
                </div>
                <div class="editor-field">
                    @Html.HiddenFor(model => model.Article.ID)
                    @Html.ValidationMessageFor(model => model.Article.ID, "You must select an article.")
                </div>
            </div>
            <div class="tab-pane" id="visual-styling">
                <div class="editor-label">
                    @Html.LabelFor(model => model.BorderColor.ID, "Border Colour")
                </div>
                <div class="editor-field">
                    @Html.DropDownList("BorderColor.ID", (SelectList)ViewBag.BorderColorIDs)
                    @Html.ValidationMessageFor(model => model.BorderColor.ID, "You must pick a Colour!")
                </div>
                <div class="editor-label">
                    <p>Selected Image: <span id="selectedImage">@((Model == null || Model.Image == null || Model.Image.Title == null) ? "None" : Model.Image.Title)</span></p>
                    <a class="btn" href="#" onclick="openResourceSelector()">Select Image</a>
                </div>
                <div class="editor-field">
                    @Html.HiddenFor(model => model.Image.ID)
                    @Html.ValidationMessageFor(model => model.Image.ID, "You must select an image to use.")
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.HeadingClass, "Heading Position")
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.HeadingClass, (SelectList)ViewBag.HeadingClasses)
                    @Html.ValidationMessageFor(model => model.HeadingClass)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.InverseHeading, "Inverse Heading (White text on black background)?")
                </div>
                <div class="editor-field">
                    @Html.CheckBoxFor(model => model.InverseHeading)
                    @Html.ValidationMessageFor(model => model.InverseHeading)
                </div>
            </div>
            <div class="tab-pane" id="position">
                <div class="editor-label">
                    @Html.LabelFor(model => model.SizeClass, "Height")
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.SizeClass, (SelectList)ViewBag.SizeClasses)
                    @Html.ValidationMessageFor(model => model.SizeClass)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Width)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.Width, (SelectList)ViewBag.Widths)
                    @Html.ValidationMessageFor(model => model.Width)
                </div>
            </div>
            <div class="tab-pane" id="advanced">
                <div class="editor-label">
                @Html.LabelFor(model => model.HeadingText, "Custom Heading Text (No More Than 150 Characters)")
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.HeadingText, new { maxlength = 150 })
                    @Html.ValidationMessageFor(model => model.HeadingText)
                </div>
                @Html.Hidden("UseHeadingText", "false")
            </div>
        </div>
        <p>&nbsp;</p>
        <p>
            <input type="submit" class="btn btn-primary" value="@((ViewBag.ButtonText != null) ? @ViewBag.ButtonText : "Save")" />
        </p>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    function openArticleSelector() {
        window.open("@Url.Action("MiniBrowser", "Article")", 'Select Article', 'height=500,width=700');
    }

    function openResourceSelector(){
        window.open("@Url.Action("MiniBrowser", "Resource", new{ filter = "image" })", 'Select Article', 'height=500,width=700');
    }

    function setArticle(id, title){
        $("#selectedArticle").html(title);
        $("[name='Article.ID']").val(id);
    }

    function setResource(id, title){
        $("#selectedImage").html(title);
        $("[name='Image.ID']").val(id);
    }

    $("form").submit(function(){
        //If we're using custom heading text, set the hidden field to true
        if($("[name='HeadingText']").val() != ""){
            $("[name='UseHeadingText']").val("true");
        }else{
            $("[name='UseHeadingText']").val("false");
        }
        return true;
    });
</script>