Review-Site/Controllers/CoreController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Review_Site.Data.Models;
using System.IO;
using System.Web.Helpers;
using Review_Site.Core;
using Review_Site.Data;
using Microsoft.Web.Helpers;
using Review_Site.Mailers;
using System.Configuration;

namespace Review_Site.Controllers
{
    public class CoreController : Controller
    {
        private readonly DataContext db = new DataContext();

        public ActionResult Index()
        {
            //if (!User.Identity.IsAuthenticated) return RedirectToAction("LandingPage");

            ViewBag.NoHeader = false;

            var category = db.Categories.Single(x => x.ID == new Guid("a323a95c-b475-4886-9f8d-006c2cc84c64"));
            var articles = category.Articles.OrderByDescending(x => x.Created).Take(5);

            return View("GetCategory", new CategoryViewModel
            {
                Category = category,
                Articles = articles,
            });
        }
        public ActionResult LandingPage()
        {
            return View();
        }

        public ActionResult Search(string query, int? page = 1)
        {
            var results = LuceneSearch.SearchDefault(query).Select(x => x.ID).ToList();

            var totalPages = (int)Math.Ceiling(results.Count() / 5d);
            if (!page.HasValue || page < 0 || page > totalPages) page = 1;

            results = results.Skip((page.Value - 1) * 5).Take(5).ToList();

            var articles = db.Articles.Get().Where(x => results.Any(y => y == x.ID)).ToList().OrderBy(x => results.IndexOf(x.ID));

            return View(new SearchViewModel
            {
                Query = query,
                Articles = articles,
                Page = page.Value,
                PageCount = totalPages
            });
        }

        public ActionResult GetResource(Guid id, int? width, int? height, bool? noSource)
        {
            //get the resource.
            var res = db.Resources.Get(id);
            if (res == null) return HttpNotFound("That resource cannot be found.");

            var path = Path.Combine(Server.MapPath("~/ResourceUploads"), id.ToString());
            var stream = new FileStream(path, FileMode.Open);
            if (stream.Length == 0) throw new HttpException(503, "An internal server error occured whilst fetching the resource.");

            Stream outputStream = stream;

            if (res.Type.StartsWith("image"))
            {
                var image = new WebImage(stream);

                if (width.HasValue && height.HasValue)
                {
                    //Resize!
                    image.Resize(width.Value, height.Value, true, true);
                }

                if (!string.IsNullOrWhiteSpace(res.Source) && noSource != true)
                {
                    image.AddTextWatermark(res.Source, "#" + ((res.SourceTextColor == null) ? "FFFFFF" : res.SourceTextColor.Value));
                }

                outputStream = new MemoryStream(image.GetBytes());
            }

            stream.Close();

            return File(outputStream, res.Type);
        }
        public ActionResult GetArticle(Guid id)
        {
            //get the article and present it!
            Article article = db.Articles.Get(id);
            if (article == null) return HttpNotFound("That article does not exist");

            PageHits.RegisterHit(article.ID);

            return View(article);
        }
        public ActionResult GetCategory(string id, int? page)
        {
            Category category;

            Guid categoryguid;
            if (Guid.TryParse(id, out categoryguid))
            {
                category = db.Categories.Get(categoryguid);
            }
            else
            {
                //Try and match to category name instead.
                var name = id.Replace('-', ' ').ToLower();
                category = db.Categories.Single(x => x.Title.ToLower() == name);
            }

            if (category == null) return HttpNotFound("That category does not exist");

            var totalPages = (int)Math.Ceiling(category.Articles.Count() / 5d);
            if (!page.HasValue || page < 0 || page > totalPages) page = 1;

            var articles = category.Articles.OrderByDescending(x => x.Created).Skip((page.Value - 1) * 5).Take(5);

            return View(new CategoryViewModel
                            {
                                Category = category,
                                Articles = articles,
                                Page = page.Value,
                                PageCount = totalPages
                            });
        }
        public ActionResult GetTag(string id, int? page)
        {
            Tag tag;

            Guid tagguid;
            if (Guid.TryParse(id, out tagguid))
            {
                tag = db.Tags.Get(tagguid);
            }
            else
            {
                //Try and match to tag name instead.
                var name = id.Replace('-', ' ').ToLower();
                tag = db.Tags.Single(x => x.Name.ToLower() == name);
            }

            if (tag == null) return HttpNotFound("That tag does not exist");

            var totalPages = (int)Math.Ceiling(tag.Articles.Count() / 5d);
            if (!page.HasValue || page < 0 || page > totalPages) page = 1;

            var articles = tag.Articles.OrderByDescending(x => x.Created).Skip((page.Value - 1) * 5).Take(5);

            return View(new TagViewModel
            {
                Tag = tag,
                Articles = articles,
                Page = page.Value,
                PageCount = totalPages
            });
        }

        public ActionResult GetGrid(string id)
        {
            Grid grid;

            Guid gridguid;
            if (Guid.TryParse(id, out gridguid))
            {
                grid = db.Grids.Get(gridguid);
            }
            else
            {
                var alias = id.ToLower();
                grid = db.Grids.Single(x => x.Alias.ToLower() == alias);

            }

            if (grid == null) return HttpNotFound("That grid does not exist");

            return View(grid);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Error(Exception e)
        {
            var httpException = e as HttpException;
            if (httpException != null)
            {
                return View("HttpError", httpException);
            }

            return Content(e.ToString());
        }
        
        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contact(ContactForm form)
        {

            //From Stack Overflow 9726576
            //Look for a proxy address first
            form.ClientAddress = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            // If there is no proxy, get the standard remote address
            if (form.ClientAddress == null || form.ClientAddress.ToLower() == "unknown")
                form.ClientAddress = Request.ServerVariables["REMOTE_ADDR"];

            if (!ReCaptcha.Validate(privateKey: ConfigurationManager.AppSettings["ReCaptcha-PrivateKey"]))
            {
                ModelState.AddModelError("", "One or more words entered in the Captcha Challenge were incorrect.");
            }

            if (!ModelState.IsValid) return View(form);

            IContactUsMailer mailer = new ContactUsMailer();

            //Email them with thanks
            mailer.ThankYou(form).Send();

            //Send to the site team
            mailer.UserContact(form).Send();

            return View("ContactThanks");
        }
    }
}

Review-Site/Views/Core/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About theREVIEW</h2>

<p>theREVIEW is produced by a group of Sixth form students from William Howard School, in Brampton, Cumbria.</p>

<p>There are about twenty people in the team who produce the magazine, all aged between 16 and 18. Writers are free to scribe about the issues that interest them: from politics, to sport, or even creative writing. </p>

<p>A new printed issue of theREVIEW student newspaper is produced once every half-term. However, reflective of the ‘dynamic’ nature of journalism today, we hope to update our website on a more frequent basis.</p>

<p>We hope you enjoy reading what we have produced.</p>

<p>Feel free to contact us using the contact link in the footer.</p>

<p>theREVIEW team</p>

Review-Site/Views/Core/Contact.cshtml
@using System.Configuration
@model Review_Site.Models.ContactForm
@{
    ViewBag.Title = "Contact Us";
    ReCaptcha.PublicKey = ConfigurationManager.AppSettings["ReCaptcha-PublicKey"];
}

<h2>Contact Us</h2>

<p>Thank you for choosing to contact theREVIEW. We value all feedback and will try to respond to your emails as quickly as possible.</p>

@using (Html.BeginForm())
{
    @Html.TextBoxFor(x => x.Name, new { placeholder="Name", @class = "span4" })<br />
    @Html.TextBoxFor(x => x.Email, new { placeholder="Email Address", @class = "span4" })<br />
    @Html.TextAreaFor(x => x.Message, new { placeholder="Please enter your message here.", @class = "offset2 span8", style = "height: 400px;" })<br />
    <p>Please prove you're human by completing the Captcha Challenge below:</p>
    @ReCaptcha.GetHtml(theme: "clean")
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Send Message</button>
    </div>
}

Review-Site/Views/Core/ContactThanks.cshtml
@{
    ViewBag.Title = "Thanks!";
}

<h2>Thank You</h2>
<p>Thank you for taking the time to write to us. We read all the mail we receive and respond to it as soon as possible.</p>
<p>&nbsp;</p>
<p><a href="@Url.Action("Index", "Core")">Site Home</a></p>

Review-Site/Views/Core/GetArticle.cshtml
@model Review_Site.Models.Article
@{
    ViewBag.Title = Model.Title;
    if(Model.Category != null) {
        ViewBag.ImageBorderColor = Model.Category.Color.Value;
    }
}
<div class="row">
    <div class="span8">
        <h1 class="article-title">@Model.Title</h1>
        <div class="article">
            <p class="article-info">
                Written by @Model.Author.FullName on the @Model.Created.ToString("dd/MM/yyyy")
                at @Model.Created.ToShortTimeString()</p>
            @{
                if (Model.LastModified.Value != Model.Created)
                {
                <p class="article-info" style="top: 20px">
                    Last edited on the @Model.LastModified.Value.ToString("dd/MM/yyyy") at @Model.LastModified.Value.ToShortTimeString()</p>
                }
            }
            <div class="article-content">
                @Html.Raw(Model.Text)
            </div>
            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style ">
                <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                <a class="addthis_button_tweet"></a>
            </div>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-5156266e43e0e6ba"></script>
            <!-- AddThis Button END -->
        </div>
    </div>
    <div class="span4">
        @Html.Partial("_Sidebar")
    </div>
</div>

Review-Site/Views/Core/GetCategory.cshtml
@model Review_Site.Data.Models.CategoryViewModel
@{
    ViewBag.Title = Model.Category.Title;
}

@if (ViewBag.NoHeader == null || ViewBag.NoHeader != false)
{
    <div class="row">
        <h2 class="large-12 columns">@Model.Category.Title</h2>
    </div>
}
else
{
    <div class="padtop">&nbsp;</div>
}

@* If the category has a grid associated with it, render it. *@
@if (Model.Category.Grid != null)
{
    @Html.Partial("_Grid", Model.Category.Grid)
}

@Html.Partial("_Articles", Model)

Review-Site/Views/Core/GetGrid.cshtml
@model Review_Site.Data.Models.Grid
@{
    ViewBag.Title = Model.Name;
}

@if (ViewBag.NoHeader == null || ViewBag.NoHeader != false)
{
    <div class="row">
        <h2 class="large-12 columns">@Model.Name</h2>
    </div>
}

@Html.Partial("_Grid", Model)

Review-Site/Views/Core/GetTag.cshtml
@model Review_Site.Data.Models.TagViewModel
@{
    ViewBag.Title = Model.Tag.Name;
}

@if (ViewBag.NoHeader == null || ViewBag.NoHeader != false)
{
    <div class="row">
        <h2 class="large-12 columns">@Model.Tag.Name</h2>
    </div>
}
else
{
    <div class="padtop">&nbsp;</div>
}

@Html.Partial("_Articles", Model)

Review-Site/Views/Core/Search.cshtml
@model Review_Site.Data.Models.SearchViewModel

@{
    ViewBag.Title = "Search";
}

<div class="row">
    <h2 class="large-12 columns">Search for @Model.Query</h2>
</div>

@Html.Partial("_Articles", Model)